/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Link from "next/link";

import {
  store,
  getPokemon,
  selectFilteredPokemon,
  selectSearch,
  rehydrate,
  setSearch,
  RootState,
  PokemonState
} from "../../src/store";

import styles from "../../styles/Home.module.css";

function Home({ initialState } : {initialState:RootState} ) {

  
  const dispatch = useDispatch();

  console.log(initialState)
  useEffect(() => {
    dispatch(rehydrate(initialState.pokemon));
  }, [dispatch, initialState]);

  const pokemon = useSelector(selectFilteredPokemon);
  const search = useSelector(selectSearch);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={search}
          onChange={(e) => {
            dispatch(setSearch(e.target.value));
          }}
          className={styles.search}
        />
        <label title="input">Search</label>

      </div>
      <div className={styles.container}>
      <h2>Pokemon List</h2>
      <div className={styles.grid}>
        {pokemon.slice(0,50).map((pokemon) => (
          <div className={styles.card} key={pokemon.id}>
            <Link href={`/pokemon-csr/${pokemon.id}`}>
              <a>
                <img
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
                  alt={pokemon.name}
                  style={{width:100,height:100}}
                />
                <h3>{pokemon.name}</h3>
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
    </div>
  );
}

export async function getServerSideProps() {
  await store.dispatch(getPokemon());
  return {
    props: {
      initialState: store.getState(),
    },
  };
}

export default Home;